### ISSUE TITLE
Too many arguments in bif.Compute() call

### ISSUE THREAD

**Issue by willemw12** [xpirt/img2sdat#1]
Error:

```
img2sdat system.new.dat2 111
Total of 215040 4096-byte output blocks in 428 input chunks.
Traceback (most recent call last):
  File "/usr/share/img2sdat/img2sdat.py", line 33, in <module>
    main(sysimg, outdir)
  File "/usr/share/img2sdat/img2sdat.py", line 13, in main
    bif.Compute('system', outdir)
TypeError: Compute() takes exactly 2 arguments (3 given)
```

Fix is to change:

```
bif.Compute('system', outdir)
```

to:

```
bif.Compute(outdir)
```

**Comment by xpirt** [comment]
fixed. thank you for your contribution.
